### PR TITLE
Fix Grammar

### PR DESCRIPTION
**Pull request by sylv256**
it was really bothering me okay

### CODE REVIEW

**Comment by sylv256** [comment]
We also may want to shorten the extraneous punctuation (e.g., "????" to "??").

# Do Not Merge Yet!

**Comment by naritanara** [comment]
Whoa, that one slipped through! Thanks for noticing.

> We also may want to shorten the extraneous punctuation (e.g., "????" to "??").

The "????" is for emphasis, I like it as it is. Did you notice any other error, or do we merge?

**Comment by sylv256** [comment]
> Whoa, that one slipped through! Thanks for noticing.
> 
> > We also may want to shorten the extraneous punctuation (e.g., "????" to "??").
> 
> The "????" is for emphasis, I like it as it is. Did you notice any other error, or do we merge?

I did find a few. I'll fix them right now.

**Comment by sylv256** [comment]
(You may merge now)

**Comment by naritanara** [comment]
Thanks for your contribution!

**Comment by naritanara** [comment]
PS: Next time you draft a PR that you don't want to get merged yet, remember GitHub allows you to mark it as WIP.

**Pull request merged**
